### ISSUE TITLE
little bug on $HOME

### ISSUE THREAD

**Issue by joaomamede** [str0g/Autodesk-Fusion360-Linux#2]
the adskidmgr-opener.desktop doesn't go where it's supposed to

This bit of code is creating .local on the folder where we run the script, and not /home/user.
I copied manually and worked.
I needed to manually run the loginKey but it started fusion360
```
xdg-mime default adskidmgr-opener.desktop x-scheme-handler/adskidmgr
  mkdir -p .local/share/Autodesk
  cp $desktop_file .local/share/autodesk/
  fi
}
```

**Comment by str0g** [comment]
Hi thanks for report, I've fixed installation.

**Comment by str0g** [comment]
please confirm that works for you and will close ticket, thanks again.
