### ISSUE TITLE
Hey Can you please tell me how to run??

### ISSUE THREAD

**Issue by Shourya-x** [str0g/Autodesk-Fusion360-Linux#3]
Hey Can you please tell me how to run?? please i am sorry to open an issue like this

**Comment by str0g** [comment]
whats the problem? (verbose description)

**Comment by Shourya-x** [comment]
Like I tried your script after the issue or login of the main installer but even after clean install I have the same problem I am on fedora 40 the issue is that I can't login to the fusion 360 desktop client . Just like the initial installer.

**Comment by str0g** [comment]
I understand that desktop integration way failed.
Have you tried manual way?
So you copy link to this directory
`❯ cat .fusion360/cache/login.txt 
adskidmgr:/login?code=<hidden>&state=<hidden>=`
and then run
./fusion_installer.sh auth

**Comment by Shourya-x** [comment]
Yes i tried this step also it still failed

**Comment by str0g** [comment]
problem is clearly in your distribution but we can try to narrow the problem.
lets start with
1. whats the output of
`cat .fusion360/cache/adskidmgr-opener.desktop `
2. whats the output of
`find .fusion360 -name AdskIdentityManager.exe -exec file {} \;`
3. whats your default browser?
4. wine version?
